#!/bin/sh

if [ $# -ne 1 ]; then
    echo "Usage: debian/source/prepare <arch>"
    exit 1
fi

TARGET=$1
GNU_TARGET=$(dpkg-architecture -a${TARGET} -qDEB_HOST_GNU_TYPE 2>/dev/null)
PKG_GNU_TARGET=$(echo ${GNU_TARGET} | sed -e 's/_/-/g')

rm -f debian/control debian/rules debian/patches/00list

sed -e "s/__PKG_GNU_TARGET__/${PKG_GNU_TARGET}/g" \
    -e "s/__TARGET__/${TARGET}/g" < debian/control.in > debian/control
sed -e "s/__PKG_GNU_TARGET__/${PKG_GNU_TARGET}/g" \
    -e "s/__GNU_TARGET__/${GNU_TARGET}/g" < debian/rules.in > debian/rules
cp debian/patches/00list.in debian/patches/00list

if [ $TARGET != mipsel ]; then
    echo 200_emit_gnu_hash >> debian/patches/00list
fi

# sleep 1

# DIR=$(basename $(pwd))
# ( cd ..; dpkg-source -b "$DIR")

